
spring:
  application:
    name: Service-Registry

server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



# spring.application.name=Service-Registry
# server.port=9092

# eureka.client.register-with-eureka=false
# eureka.client.fetch-registry=false


