
server:
  port: 9095

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DikshaSharma11oct/microservice-config-server
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# to access service use this url
# http://192.168.1.37:9095/actuator/PROD